plugins:
  checkstyle:
    enabled: true
  csslint:
    enabled: true
  editorconfig:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  pmd:
    enabled: true
  shellcheck:
    enabled: true
  sonar-java:
    enabled: true
  stylelint:
    enabled: true  

exclude_patterns:
  - "config/""
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "mvnw"
  - "mvnw.cmd"