language: 
  - java

addons:
  sonarcloud:
    organization: "chandlerlucius-github"
    
before_install:
  #Create rsa key from encrypted key and add it to ssh properties
  - openssl aes-256-cbc -K $encrypted_46f1dd837efd_key -iv $encrypted_46f1dd837efd_iv -in id_rsa.enc -out id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 id_rsa
  - ssh-add id_rsa

before_script:
  #Install kcov dependencies, make/install kcov, remove uneeded directories
  - sudo apt-get install binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev build-essential cmake make -y
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz
  - cd kcov-master
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../
  - rm -rf kcov-master
  - rm -rf target/kcov
  #Install FOSSA analyzer
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  #Run linting tools, java tests, javascript tests, and shell tests
  - ./mvnw test -B

after_script:
  #Run kcov to collect bash code coverage and report to coveralls
  - kcov --bash-dont-parse-binary-dir --path-strip-level=1 --include-pattern=src/ target/kcov bats src/test/sh/
  #Scan code with sonarcloud
  - sonar-scanner
  #Upload code coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
  #Verify dependency licenses through FOSSA
  - fossa init
  - fossa analyze

deploy:
  provider: script
  skip_cleanup: true
  script: 
    rsync -avvz -e "ssh -p 7001 -o StrictHostKeyChecking=no -o ConnectTimeout=5" target/linux-dashboard-1.0.0.jar clucius@linuxdashboard.com:~ && 
    ssh -f -p 7001 -o StrictHostKeyChecking=no -o ConnectTimeout=5 clucius@linuxdashboard.com "sh -c 'pkill -9 -f linux-dashboard'" &&
    ssh -f -p 7001 -o StrictHostKeyChecking=no -o ConnectTimeout=5 clucius@linuxdashboard.com "sh -c 'nohup java -jar linux-dashboard-1.0.0.jar >/dev/null 2>&1 &'" 
  on:
    branch: master